### ISSUE TITLE
No front end?

### ISSUE THREAD

**Issue by Turkzilla** [marselbairam/medium-clone#1]
Any documentation on how to use the API or code for front-end? Currently, all endpoints are returning 500 error.
Sample: "TypeError: Cannot read property 'constructor' of null
    at ValidationExecutor.execute"

**Comment by marselbairam** [comment]
> Any documentation on how to use the API or code for front-end?

https://codebase.show/projects/realworld
Use any ready project from here and replace api_url in environment.

**Comment by Turkzilla** [comment]
> > Any documentation on how to use the API or code for front-end?
> 
> https://codebase.show/projects/realworld Use any ready project from here and replace api_url in environment.

I just wanted to test the API itself. All swagger tests are returning error. I did run db:create, db:seed before running the API.
